### ISSUE TITLE
Issue when Deploying to Netflify

### ISSUE THREAD

**Issue by KnightWebnApps** [langbamit/svelte-scrollto#2]
It works fine in development but when i try to deploy it fails with this message

6:01:38 AM: /opt/build/repo/node_modules/svelte-scrollto/src/index.js:1
6:01:38 AM: import * as easings from "svelte/easing";
6:01:38 AM:        ^
6:01:38 AM: SyntaxError: Unexpected token *
6:01:38 AM:     at Module._compile (internal/modules/cjs/loader.js:723:23)
6:01:38 AM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
6:01:38 AM:     at Module.load (internal/modules/cjs/loader.js:653:32)
6:01:38 AM:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
6:01:38 AM:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
6:01:38 AM:     at Module.require (internal/modules/cjs/loader.js:692:17)
6:01:38 AM:     at require (internal/modules/cjs/helpers.js:25:18)
6:01:38 AM:     at Object.<anonymous> (/opt/build/repo/__sapper__/build/server/server.js:1:1554)
6:01:38 AM:     at e (/opt/build/repo/__sapper__/build/server/server.js:1:124)
6:01:38 AM:     at Module.<anonymous> (/opt/build/repo/__sapper__/build/server/server.js:1:19876)
6:01:43 AM: > timed out waiting for connection`

It was installed using npm maybe trying yarn will work

**Comment by KnightWebnApps** [comment]
worked when i used yarn
