### ISSUE TITLE
import cubicInOut server crashed

### ISSUE THREAD

**Issue by OfficialOzzy** [langbamit/svelte-scrollto#5]
Hi, 

I am running npm run dev with Sapper / Svelte, I have installed your scroll to package via NPM but keep getting this issue:

```
/home/XXXX/node_modules/svelte-scrollto/src/index.js:1
import { cubicInOut } from "svelte/easing";
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/XXXX/__sapper__/dev/server/server.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> Server crashed
```

**Comment by itanio** [comment]
Can confirm, I am getting this today too. Has been previously working, and there was no change on my end that I can find.

**Comment by christhorp** [comment]
+ 1. I'm getting the error: SyntaxError: Cannot use import statement outside a module

import { cubicInOut } from "svelte/easing";
^^^^^^

```
SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Applications/MAMP/htdocs/local.rhd-frontend.com/__sapper__/dev/server/server.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
```

**Comment by eikaramba** [comment]
jep not working in svelte-kit

**Comment by vhollo** [comment]
Moving to the dependencies (from devDeps) solved this issue in SvelteKit.

**Comment by DarthJonathan** [comment]
> Moving to the dependencies (from devDeps) solved this issue in SvelteKit.

what dependencies did you move?

**Comment by vhollo** [comment]
> > Moving to the dependencies (from devDeps) solved this issue in SvelteKit.
> 
> 
> 
> what dependencies did you move?

svelte-scrollto

**Comment by jordankittle** [comment]
I am experiencing this same error. Moving to dependencies instead of dev dependencies did not help.
